version: '3.8'
services:
  web:
    build: .
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      # Pass through from system or .env file in this directory
      - RAG_API_KEY=${RAG_API_KEY}
    restart: always
