
name: CI/CD on Self‑Hosted Runner

on:
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Set up Node (no caching for now)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::npm ci"
          npm ci
          echo "::endgroup::"

      # Build Next.js app
      - name: Build Next.js App
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::npm run build"
          npm run build
          echo "::endgroup::"

      # Tear down previous stack
      - name: Tear down previous stack
        shell: bash -euxo pipefail {0}
        run: docker compose -f compose.yml down --remove-orphans || true

      # Build & deploy Docker containers
      - name: Build & Deploy Docker containers
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::docker compose build (web)"
          docker compose -f compose.yml build --no-cache --progress=plain web
          echo "::endgroup::"

          echo "::group::docker compose up (web)"
          docker compose -f compose.yml up -d web
          echo "::endgroup::"
