
name: CI/CD on Self‑Hosted Runner

on:
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: env
    env:
      RAG_API_KEY: ${{ secrets.RAG_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      # Tear down previous stack
      - name: Tear down previous stack
        shell: bash -euxo pipefail {0}
        run: docker compose -f docker-compose.yml down --remove-orphans || true

      # Build & deploy Docker containers
      - name: Build & Deploy Docker containers
        shell: bash -euxo pipefail {0}
        run: |
          echo "::group::docker compose build (web)"
          docker compose -f docker-compose.yml build --no-cache --progress=plain web
          echo "::endgroup::"

          echo "::group::docker compose up (web)"
          docker compose -f docker-compose.yml up -d web
          echo "::endgroup::"
